name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml

      - name: Restore dependencies
        run: dotnet restore ./src/VulnerableApi/VulnerableApi.csproj

      - name: Build
        run: dotnet build ./src/VulnerableApi/VulnerableApi.csproj --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./src/VulnerableApi/VulnerableApi.csproj -c Release -o ./publish

      - name: Build Docker image
        run: docker build -t vulnerable-api:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'vulnerable-api:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
